/* eslint-disable import/prefer-default-export */
export const INSERT_EXPENDITURE = "INSERT_EXPENDITURE";
export const ASSIGN_EXPENDITURES = "ASSIGN_EXPENDITURES";
export const DELETE_EXPENDITURE = "DELETE_EXPENDITURE";
export const UPDATE_EXPENDITURE = "UPDATE_EXPENDITURE";

export const ASSIGN_REVENUES = "ASSIGN_REVENUES";
export const INSERT_REVENUE = "INSERT_REVENUE";
export const DELETE_REVENUE = "DELETE_REVENUE";
export const UPDATE_REVENUE = "UPDATE_REVENUE";

export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_CURRENT_NOTIFICATION = "CLEAR_CURRENT_NOTIFICATION";

export const UPDATE_CATEGORY_FILTER = "UPDATE_CATEGORY_FILTER";
export const UPDATE_DATERANGE_FILTER = "UPDATE_DATERANGE_FILTER";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
