/* eslint-disable import/prefer-default-export */
export const INSERT_EXPENDITURE = "INSERT_EXPENDITURE";
export const ASSIGN_EXPENDITURES = "ASSIGN_EXPENDITURES";
export const DELETE_EXPENDITURE = "DELETE_EXPENDITURE";
export const UPDATE_EXPENDITURE = "UPDATE_EXPENDITURE";

export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_CURRENT_NOTIFICATION = "CLEAR_CURRENT_NOTIFICATION";

export const SET_NAME = "SET_NAME";
export const SET_DATE = "SET_DATE";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_COST = "SET_COST";
export const FETCH_EXPENDITURE = "FETCH_EXPENDITURE";
export const ERASE_FORM_DATA = "ERASE_FORM_DATA";
