/* eslint-disable import/prefer-default-export */
export const INSERT_EXPENDITURE = "INSERT_EXPENDITURE";
export const ASSIGN_EXPENDITURES = "ASSIGN_EXPENDITURES";
export const DELETE_EXPENDITURE = "DELETE_EXPENDITURE";

export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_CURRENT_NOTIFICATION = "CLEAR_CURRENT_NOTIFICATION";

